foreground              __color05__
background              __color00__
selection_foreground    __color00__
selection_background    __color0C__
cursor                  __color0D__
cursor_text_color       __color00__
active_tab_foreground   __color00__
active_tab_background   __color0D__
inactive_tab_foreground __color04__
inactive_tab_background __color01__

# Black
color0  __color01__
color8  __color03__

# Red
color1  __color08__
color9  __color08__

# Green
color2  __color0B__
color10 __color0B__

# Yellow
color3  __color0A__
color11 __color0A__

# Blue
color4  __color0D__
color12 __color0D__

# Magenta
color5  __color0E__
color13 __color0E__

# Cyan
color6  __color0C__
color14 __color0C__

# White
color7  __color05__
color15 __color06__
