-- Neovim theme + statusline (generated by theme-switch)
local bg      = "__color00__"
local bg2     = "__color01__"
local bg3     = "__color02__"
local fg      = "__color05__"
local fg2     = "__color04__"
local muted   = "__color03__"
local accent  = "__color0D__"
local cyan    = "__color0C__"
local green   = "__color0B__"
local yellow  = "__color0A__"
local red     = "__color08__"
local magenta = "__color0E__"

-- Highlight groups
vim.api.nvim_set_hl(0, "StatusModeNormal",  { bg = accent,  fg = bg, bold = true })
vim.api.nvim_set_hl(0, "StatusModeInsert",  { bg = green,   fg = bg, bold = true })
vim.api.nvim_set_hl(0, "StatusModeVisual",  { bg = magenta, fg = bg, bold = true })
vim.api.nvim_set_hl(0, "StatusModeCommand", { bg = yellow,  fg = bg, bold = true })
vim.api.nvim_set_hl(0, "StatusModeReplace", { bg = red,     fg = bg, bold = true })
vim.api.nvim_set_hl(0, "StatusFile",        { bg = bg2,     fg = fg, bold = true })
vim.api.nvim_set_hl(0, "StatusInfo",        { bg = bg2,     fg = cyan })
vim.api.nvim_set_hl(0, "StatusBase",        { bg = bg,      fg = fg2 })
vim.api.nvim_set_hl(0, "StatusGitBranch",   { bg = bg2,     fg = green })

-- Git branch (cached, updated on BufEnter)
local git_branch = ""
vim.api.nvim_create_autocmd({"BufEnter", "BufWritePost"}, {
  callback = function()
    local ok, job = pcall(vim.fn.jobstart, "git -C " .. vim.fn.expand("%:h") .. " rev-parse --abbrev-ref HEAD 2>/dev/null", {
      on_stdout = function(_, data)
        git_branch = vim.trim(data[1] or "")
        vim.cmd("redrawstatus")
      end,
      stdout_buffered = true,
    })
    if not ok then git_branch = "" end
  end,
})

-- Statusline
function _G.ThemeStatusline()
  local mode_map = {
    n  = { "NORMAL",  "StatusModeNormal" },
    i  = { "INSERT",  "StatusModeInsert" },
    v  = { "VISUAL",  "StatusModeVisual" },
    V  = { "V-LINE",  "StatusModeVisual" },
    ["\22"] = { "V-BLOCK", "StatusModeVisual" },
    c  = { "COMMAND", "StatusModeCommand" },
    R  = { "REPLACE", "StatusModeReplace" },
  }
  local m = mode_map[vim.fn.mode()] or { vim.fn.mode():upper(), "StatusModeNormal" }

  local filename = vim.fn.expand("%:t")
  if filename == "" then filename = "[No Name]" end

  local ft = vim.bo.filetype
  local line = vim.fn.line(".")
  local col = vim.fn.col(".")
  local total = vim.fn.line("$")

  local parts = {}

  -- Mode
  table.insert(parts, "%#" .. m[2] .. "# " .. m[1] .. " ")

  -- Filename
  table.insert(parts, "%#StatusFile# " .. filename .. " ")

  -- Git branch
  if git_branch ~= "" then
    table.insert(parts, "%#StatusGitBranch# " .. git_branch .. " ")
  end

  -- Right side: filetype + position
  table.insert(parts, "%=")
  table.insert(parts, "%#StatusInfo# " .. ft .. " ")
  table.insert(parts, "%#StatusBase# " .. line .. ":" .. col .. " /" .. total .. " ")

  return table.concat(parts)
end

vim.opt.statusline = "%!v:lua.ThemeStatusline()"

-- Diagnostic signs with theme colors
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = red })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = yellow })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = cyan })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = green })
