-- Neovim theme colors (generated by theme-switch; loaded by init.lua via pcall dofile)
local bg      = "__color00__"
local bg2     = "__color01__"
local bg3     = "__color02__"
local fg      = "__color05__"
local fg2     = "__color04__"
local muted   = "__color03__"
local accent  = "__color0D__"
local cyan    = "__color0C__"
local green   = "__color0B__"
local yellow  = "__color0A__"
local red     = "__color08__"
local magenta = "__color0E__"

-- Highlight groups
vim.api.nvim_set_hl(0, "StatusModeNormal",  { bg = accent,  fg = bg, bold = true })
vim.api.nvim_set_hl(0, "StatusModeInsert",  { bg = green,   fg = bg, bold = true })
vim.api.nvim_set_hl(0, "StatusModeVisual",  { bg = magenta, fg = bg, bold = true })
vim.api.nvim_set_hl(0, "StatusModeCommand", { bg = yellow,  fg = bg, bold = true })
vim.api.nvim_set_hl(0, "StatusModeReplace", { bg = red,     fg = bg, bold = true })
vim.api.nvim_set_hl(0, "StatusFile",        { bg = bg2,     fg = fg, bold = true })
vim.api.nvim_set_hl(0, "StatusModified",    { bg = bg2,     fg = yellow, bold = true })
vim.api.nvim_set_hl(0, "StatusInfo",        { bg = bg2,     fg = cyan })
vim.api.nvim_set_hl(0, "StatusBase",        { bg = bg,      fg = fg2 })
vim.api.nvim_set_hl(0, "StatusGitBranch",   { bg = bg2,     fg = green })

-- Diagnostic signs with theme colors
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = red })
vim.api.nvim_set_hl(0, "DiagnosticWarn",  { fg = yellow })
vim.api.nvim_set_hl(0, "DiagnosticInfo",  { fg = cyan })
vim.api.nvim_set_hl(0, "DiagnosticHint",  { fg = green })
