theme_background = False   # Default terminal colors
rounded_corners = True     # Rounded corners
proc_tree = True           # Show processes in tree
graph_symbol = "braille"   # Graphics drawing symbols (braille, block)
proc_sorting = "cpu lazy"  # Sorts for CPU usage
