foreground              __colorforeground1__
background              __colorbackground1__
selection_foreground    __colorbackground1__
selection_background    __colorbrightcyan__
cursor                  __coloraccent__
cursor_text_color       __colorbackground1__
active_tab_foreground   __colorbackground1__
active_tab_background   __coloraccent__
inactive_tab_foreground __colorforeground2__
inactive_tab_background __colorbackground2__

# Black
color0  __colorblack__
color8  __colorbrightblack__

# Red
color1  __colorred__
color9  __colorbrightred__

# Green
color2  __colorgreen__
color10 __colorbrightgreen__

# Yellow
color3  __coloryellow__
color11 __colorbrightyellow__

# Blue
color4  __colorblue__
color12 __colorbrightblue__

# Magenta
color5  __colormagenta__
color13 __colorbrightmagenta__

# Cyan
color6  __colorcyan__
color14 __colorbrightcyan__

# White
color7  __colorwhite__
color15 __colorbrightwhite__
