[mgr]
cwd = { fg = "__colorbrightcyan__" }
find_keyword = { fg = "__colorbrightgreen__", bold = true }
find_position = { fg = "__colorbrightmagenta__" }
marker_selected = { fg = "__colorbrightyellow__" }
marker_copied = { fg = "__colorbrightgreen__" }
marker_cut = { fg = "__colorred__" }
count_copied = { fg = "__colorbackground1__", bg = "__colorbrightgreen__" }
count_cut = { fg = "__colorbackground1__", bg = "__colorred__" }
count_selected = { fg = "__colorbackground1__", bg = "__colorbrightyellow__" }
border_style = { fg = "__colorforeground2__" }
syntect_theme = "~/.config/yazi/syntect.tmTheme"

[indicator]
current = { bg = "__colorbackground3__", bold = true }
preview = { bg = "__colorbackground3__", bold = true }

[tabs]
active = { fg = "__colorbackground1__", bg = "__coloraccent__", bold = true }
inactive = { fg = "__coloraccent__", bg = "__colorbackground2__" }

[mode]
normal_main = { fg = "__colorbackground1__", bg = "__coloraccent__", bold = true }
normal_alt = { fg = "__coloraccent__", bg = "__colorbackground1__" }
select_main = { fg = "__colorbackground1__", bg = "__colorbrightgreen__", bold = true }
select_alt = { fg = "__colorbrightgreen__", bg = "__colorbackground1__" }
unset_main = { fg = "__colorbackground1__", bg = "__coloraccent3__", bold = true }
unset_alt = { fg = "__coloraccent3__", bg = "__colorbackground1__" }

[status]
perm_type = { fg = "__coloraccent__" }
perm_read = { fg = "__colorbrightyellow__" }
perm_write = { fg = "__colorred__" }
perm_exec = { fg = "__colorbrightgreen__" }
perm_sep = { fg = "__colorbrightcyan__" }
progress_label = { fg = "__colorforeground1__", bold = true }
progress_normal = { fg = "__colorbrightgreen__" }
progress_error = { fg = "__colorred__", bold = true }

[which]
mask = { bg = "__colorbackground3__" }
cand = { fg = "__colorbrightcyan__" }
rest = { fg = "__coloraccent3__" }
desc = { fg = "__colorforeground1__" }
separator_style = { fg = "__colorforeground2__" }

[confirm]
border = { fg = "__coloraccent__" }
title = { fg = "__colorforeground1__" }
body = { fg = "__colorforeground1__" }
list = { fg = "__colorforeground1__" }
btn_yes = { fg = "__colorbrightgreen__", bold = true }
btn_no = { fg = "__colorred__", bold = true }

[spot]
border = { fg = "__coloraccent__" }
title = { fg = "__colorforeground1__" }
tbl_col = { bg = "__colorbackground3__" }
tbl_cell = { fg = "__colorforeground1__" }

[notify]
title_info = { fg = "__colorbrightcyan__" }
title_warn = { fg = "__colorbrightyellow__" }
title_error = { fg = "__colorred__", bold = true }

[pick]
border = { fg = "__coloraccent__" }
active = { fg = "__colorbrightmagenta__" }
inactive = { fg = "__colorforeground1__" }

[input]
border = { fg = "__coloraccent__" }
title = { fg = "__colorforeground1__" }
value = { fg = "__colorforeground1__" }
selected = { bg = "__colormuted__" }

[cmp]
border = { fg = "__coloraccent__" }
active = { fg = "__colorbrightmagenta__", bg = "__colormuted__" }
inactive = { fg = "__colorforeground1__" }

[tasks]
border = { fg = "__coloraccent__" }
title = { fg = "__colorforeground1__" }
hovered = { fg = "__colorforeground1__", bg = "__colormuted__" }

[help]
border = { fg = "__coloraccent__" }
chord = { fg = "__colorbrightmagenta__" }
action = { fg = "__colorbrightcyan__" }
hovered = { fg = "__colorforeground1__", bg = "__colormuted__" }

[filetype]
rules = [
  { mime = "image/*", fg = "__colorbrightcyan__" },
  { mime = "video/*", fg = "__colorbrightyellow__" },
  { mime = "audio/*", fg = "__colorbrightyellow__" },
  { mime = "inode/x-empty", fg = "__colorbrightcyan__" },
  { mime = "application/zip", fg = "__colorbrightmagenta__" },
  { mime = "application/gzip", fg = "__colorbrightmagenta__" },
  { mime = "application/tar", fg = "__colorbrightmagenta__" },
  { mime = "application/bzip", fg = "__colorbrightmagenta__" },
  { mime = "application/bzip2", fg = "__colorbrightmagenta__" },
  { mime = "application/7z-compressed", fg = "__colorbrightmagenta__" },
  { mime = "application/rar", fg = "__colorbrightmagenta__" },
  { mime = "application/xz", fg = "__colorbrightmagenta__" },
  { mime = "application/doc", fg = "__colorbrightgreen__" },
  { mime = "application/pdf", fg = "__colorbrightgreen__" },
  { mime = "application/rtf", fg = "__colorbrightgreen__" },
  { mime = "application/vnd.*", fg = "__colorbrightgreen__" },
  { url = "*/", fg = "__coloraccent__", bold = true },
  { url = "*", fg = "__colorforeground1__" },
]

prepend_conds = [
  { if = "orphan", text = "", fg = "__colorforeground1__" },
  { if = "link", text = "", fg = "__colorforeground2__" },
  { if = "block", text = "", fg = "__colorbrightyellow__" },
  { if = "char", text = "", fg = "__colorbrightyellow__" },
  { if = "fifo", text = "", fg = "__colorbrightyellow__" },
  { if = "sock", text = "", fg = "__colorbrightyellow__" },
  { if = "sticky", text = "", fg = "__colorbrightyellow__" },
  { if = "dummy", text = "", fg = "__colorred__" },
  { if = "dir", text = "", fg = "__coloraccent__" },
  { if = "exec", text = "", fg = "__colorbrightgreen__" },
  { if = "!dir", text = "", fg = "__colorforeground1__" },
]
[icon]
prepend_dirs = [
  { name = ".config", text = "", fg = "__colororange__" },
  { name = ".git", text = "", fg = "__colorbrightcyan__" },
  { name = ".npm", text = "", fg = "__coloraccent__" },
  { name = "Media", text = "", fg = "__colorbrightcyan__" },
  { name = "Desktop", text = "", fg = "__colorbrightcyan__" },
  { name = "Documents", text = "", fg = "__colorbrightcyan__" },
  { name = "Downloads", text = "", fg = "__colorbrightcyan__" },
  { name = "Games", text = "󰊴", fg = "__colorbrightcyan__" },
  { name = "Books", text = "", fg = "__colorbrightcyan__" },
  { name = "Music", text = "", fg = "__colorbrightcyan__" },
  { name = "Nixos", text = "", fg = "__colorbrightcyan__" },
  { name = "Pictures", text = "", fg = "__colorbrightcyan__" },
  { name = "Projects", text = "", fg = "__colorbrightcyan__" },
  { name = "Videos", text = "", fg = "__colorbrightcyan__" },
]

prepend_conds = [
  { if = "orphan", text = "", fg = "__colorforeground1__" },
  { if = "link", text = "", fg = "__colorforeground2__" },
  { if = "block", text = "", fg = "__colorbrightyellow__" },
  { if = "char", text = "", fg = "__colorbrightyellow__" },
  { if = "fifo", text = "", fg = "__colorbrightyellow__" },
  { if = "sock", text = "", fg = "__colorbrightyellow__" },
  { if = "sticky", text = "", fg = "__colorbrightyellow__" },
  { if = "dummy", text = "", fg = "__colorred__" },
  { if = "dir", text = "", fg = "__coloraccent__" },
  { if = "exec", text = "", fg = "__colorbrightgreen__" },
  { if = "!dir", text = "", fg = "__colorforeground1__" },
]
