foreground            #A9B1D6
background            #1A1B26
selection_foreground  #A9B1D6
selection_background  #343B58
url_color             #73DACA
cursor                #C0CAF5

# black
color 0  #15161E
color 8  #414868

# red
color 1  #F7768E
color 9  #F7768E

# green
color 2  #73DACA
color 10 #73DACA

# yellow
color 3  #E0AF68
color 11 #E0AF68

# blue
color 4  #7AA2F7
color 12 #7AA2F7

# magenta
color 5  #BB9AF7
color 13 #BB9AF7

# cyan
color 6  #B4F9F8
color 14 #B4F9F8

# white
color 7  #C0CAF5
color 15 #C0CAF5
