# Theme: Everforest (dark, medium)
name="Everforest"
wallpaper="everforestGiantForest.png"
gtk_theme="Everforest"
kvantum_theme="Everforest"
gtk_dark="1"
opencode_theme="everforest"
btop_theme="everforest-dark-medium"
cursor_theme="Phinger Cursors (Everforest)"
color00="#2d353b"
color01="#343f44"
color02="#3d484d"
color03="#859289"
color04="#9da9a0"
color05="#d3c6aa"
color06="#e9e8d2"
color07="#83c092"
color08="#e67e80"
color09="#e69875"
color0A="#dbbc7f"
color0B="#a7c080"
color0C="#83c092"
color0D="#7fbbb3"
color0E="#d699b6"
color0F="#708089"
