# Theme: Nord
name="Nord"
wallpaper="nordFirewatch.png"
gtk_theme="Nordic"
kvantum_theme="Nordic"
gtk_dark="1"
opencode_theme="nord"
btop_theme="nord"
cursor_theme="Capitaine Cursors (Nord)"
color00="#2e3440"
color01="#3b4252"
color02="#434c5e"
color03="#4c566a"
color04="#d8dee9"
color05="#e5e9f0"
color06="#eceff4"
color07="#8fbcbb"
color08="#bf616a"
color09="#d08770"
color0A="#ebcb8b"
color0B="#a3be8c"
color0C="#88c0d0"
color0D="#81a1c1"
color0E="#b48ead"
color0F="#5e81ac"
